wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.7.9
      5: 0.10.20
      8:
      - 1
      - 5
augmentation:
  desc: null
  value: []
batch_size:
  desc: null
  value: 28
device:
  desc: null
  value: cuda
loss:
  desc: null
  value: segmentation_models_pytorch.utils.losses.DiceLoss
model:
  desc: null
  value: efficientnet-b0
model_path:
  desc: null
  value: ../models/efficientnet-b0
name:
  desc: null
  value: efficientnet-b0
num_epochs:
  desc: null
  value: 20
optimizer:
  desc: null
  value: torch.optim.adam.Adam
path:
  desc: null
  value: ../data/normal2
pretrain:
  desc: null
  value: imagenet
scheduler:
  desc: null
  value: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
seed:
  desc: null
  value: 1015
